# Generated by Django 2.1.3 on 2018-11-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20181112_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='description',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='upload_date',
            new_name='pub_date',
        ),
    ]
